# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cddm5jWFclG2d954R0p9GqapeKdyH5dL
"""

while True:
    Nome = input("Digite seu nome completo: ")
    while True:
        idade_str = input("Digite sua idade (apenas números): ")
        if idade_str.isdigit():
            Idade = int(idade_str)
            break
        else:
            print("Entrada inválida! Digite apenas números inteiros.")
    if Idade < 0:
        print("Idade Inválida")
    elif Idade <= 12:
        print(f"{Nome} você ainda é uma criançinha, que fofura.")
    elif Idade <= 17:
        print(f"{Nome} você já está grande, começando a ter responsabilidade. Essa fase de adolescente muito boa.")
    elif Idade <= 59:
        print(f"É {Nome}, tá ficando com dor nas costas já né!? Difícil ser adulto.")
    else:
        print(f"Já se aponsentou {Nome}? kkkk ser idoso tem suas vantagens.")
    break